import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kyve: Your digital shield",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100 dark:bg-dark-1`}>
      
        <div className='w-full flex justify-center items-center min-h-screen  max-w-4xl'>
          {children}
        </div> 
      
      </body>
    </html>
  );
}